# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm8150-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter andromeda cepheus crux nabu raphael vayu,$(TARGET_DEVICE)),)

endif
